export const GET_MOVIE_LIST = "GET_MOVIE_LIST";
export const GET_BANNER_LIST = "GET_BANNER_LIST";
export const GET_ACTIVITY_INFO = "GET_ACTIVITY_INFO";
export const GET_PROJECT_SHOP_INFO = "GET_PROJECT_SHOP_INFO";